allowBuilds:
  better-sqlite3: set this to true or false
  electron: set this to true or false
  esbuild: set this to true or false
  lzma-native: set this to true or false
minimumReleaseAgeExclude:
  - '@nssai/scheduler@0.1.0'
